stages:
  #- build
  - publish

building:
  stage: build
  script:
    - npm install
    - npm run build publish

publishing:
  stage: publish
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
